FROM golang:1.23.4-alpine3.21 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/app ./tools/turn

FROM alpine
WORKDIR /src
COPY --from=builder /bin/app /bin/app
ENTRYPOINT ["./bin/app"]